import { Geist, Geist_Mono } from "next/font/google";


export const metadata = {
  title: "about",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        children
  );
}
